name: Development Workflow

on:
  pull_request:
    branches: [ dev, main ]

jobs:

  trivy-fs-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        exit-code: '1'
        version: 'latest'
        format: 'table'
        ignore-unfixed: true
        hide-progress: true

  node-unittests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["22.20.0"]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.20.0'
    - name: Install node dependencies
      run: npm ci
    - name: Test with unittest
      run: npm test